# Maaz ur Rehman
# Assignment of Linear Algebra

Q.1) Additon of Vector

In [1]:
import numpy

In [2]:
a = numpy.array([1,2,3])
b = numpy.array([4,0,-5])
print(a+b)

[ 5  2 -2]


Q.2) Vector space property (associative property)

In [3]:
u = numpy.array([5,2,7])
v = numpy.array([8,9,3])
w = numpy.array([1,4,6])
a = (u + v) + w
b = u+ (v + w)
print(a)
print(b)
print("if a = b it's mean associative property is proof ")

[14 15 16]
[14 15 16]
if a = b it's mean associative property is proof 


Q.3) Dot product

In [4]:
u = numpy.array([1,2,3])
v = numpy.array([4,5,6])
answer = (u[0] * v[0]) + (u[1] * v[1]) + (u[2] * v[2]) 
print("u.v =" ,answer)


u.v = 32


Q.4) Scalar Multiplication

In [5]:
u = numpy.array([1,2,3])
ans = 2 * u
print(ans)

[2 4 6]


Q.5) Transpose of Matrix

In [6]:
a = numpy.array([[1,2],[3,4]])
print('the transpose of a matrix is')
print( a.transpose())

the transpose of a matrix is
[[1 3]
 [2 4]]


Q.6) Addition of Matrix

In [7]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]

for r in result:
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [8]:
# with using numpy Addition of two matrix
x = numpy.array([[12,7,3], 
                [4 ,5,6],
                [7 ,8,9]])
y = numpy.array([[5,8,1],
                [6,7,3],
                [4,5,9]])
C = x + y      # element wise addition
print(C)


[[17 15  4]
 [10 12  9]
 [11 13 18]]


Q.7) Multiplication of Martix

In [9]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x3 matrix
Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]
#the result is 3x3
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]


for i in range(len(X)):
   
   for j in range(len(Y[0])):
        
       
       for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)

[114, 160, 60]
[74, 97, 73]
[119, 157, 112]


In [11]:
# with using numpy Multiplication of two matrix
A = numpy.array([[12,7,3],
                 [4 ,5,6],
                [7 ,8,9]])
B = numpy.array([[5,8,1],
                 [6,7,3],
                 [4,5,9]])
C = A.dot(B)
print(C)

[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


Q.8) Unit Vector

In [ ]:
import math
val = eval(input("Enter number of values: "))
ul = []
result = []
for i in range(val):
    u = eval(input("Enter u"+str(i+1)+": "))
    ul.append(u)
    mul = ul[i] * ul[i]
    result.append(mul)
    print("The of u is: ", ul)
    print("The square of u is : ", result)
    ans = 0
    for i in result:
        ans = ans + i
        print("||u|| : \u221A or", ans)
        print("||u|| : ", math.sqrt(ans))
        for i in ul:
            print(" ( "+str(i) + " / " + "\u221A" + str(ans) + " )", end="")

Enter number of values: 12
Enter u1: 12
The of u is:  [12]
The square of u is :  [144]
||u|| : √ or 144
||u|| :  12.0
 ( 12 / √144 )Enter u2: 12
The of u is:  [12, 12]
The square of u is :  [144, 144]
||u|| : √ or 144
||u|| :  12.0
 ( 12 / √144 ) ( 12 / √144 )||u|| : √ or 288
||u|| :  16.97056274847714
 ( 12 / √288 ) ( 12 / √288 )Enter u3: 14
The of u is:  [12, 12, 14]
The square of u is :  [144, 144, 196]
||u|| : √ or 144
||u|| :  12.0
 ( 12 / √144 ) ( 12 / √144 ) ( 14 / √144 )||u|| : √ or 288
||u|| :  16.97056274847714
 ( 12 / √288 ) ( 12 / √288 ) ( 14 / √288 )||u|| : √ or 484
||u|| :  22.0
 ( 12 / √484 ) ( 12 / √484 ) ( 14 / √484 )